version: '3'

volumes:
  postgres_data: {}
  postgres_backup: {}

services:
  db:
    container_name: andela_social_db
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    restart: always
    environment:
      - POSTGRES_PASSWORD=a_socials
      - POSTGRES_DB=a_socials
      - POSTGRES_USER=a_socials
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    ports:
      - "5432"

  web:
    image: andela_social:1.0
    container_name: andela_social
    env_file:
      - .env
    build:
      context: ./docker/django
      dockerfile: Dockerfile
    command: /setup-dev.sh
    depends_on:
      - db
    ports:
      - "8000:8000"
    links:
      - db
    volumes:
      - .:/andela_social





