version: '3'

volumes:
  postgres_data: {}
  postgres_backup: {}

services:
  db:
    container_name: andela_social_db
    build:
      context: ./docker/database
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    ports:
      - "5432"

  server:
    container_name: andela_social_server
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    command: /start-server.sh
    depends_on:
      - db
    ports:
      - "8000:8000"
    links:
      - db
    volumes:
      - .:/andela_social
  client:
    container_name: andela_social_client
    build:
      context: .
      dockerfile: ./docker/client/Dockerfile
    command: /start-client.sh
    volumes:
      - .:/andela_social
    env_file:
      - .env
    depends_on:
      - server
    ports:
      - "9000:9000"




