# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-25 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_event_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='andelauserprofile',
            name='state',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='andelauserprofile',
            name='token',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
