# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-05-31 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_event_slack_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(default=0, max_length=50)),
                ('start_date', models.CharField(max_length=50)),
                ('end_date', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Recurrence'),
        ),
    ]
