# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-08-13 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20190711_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(choices=[('Egypt', 'Egypt'), ('Nigeria', 'Nigeria'), ('Uganda', 'Uganda'), ('Kenya', 'Kenya'), ('San-Fransisco', 'San-Fransisco'), ('Kigali', 'Kigali')], default='San-Fransisco', max_length=50),
        ),
    ]
