version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
      - image: circleci/postgres:9.4
        environment:
          - POSTGRES_USER: circleci
          - POSTGRES_DB: circlecidb
          - POSTGRES_PASSWORD: $DB_PASSWORD



    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r server/requirements.txt

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            export DJANGO_SETTINGS_MODULE=a_socials.settings.dev
            python server/manage.py test --snapshot-update server/api/tests/ server/graphql_schemas/tests/

      - store_artifacts:
          path: test-reports
          destination: test-reports

  deploy:
    docker:
      - image: circleci/python:3.6.4
        environment:
          TERM: xterm-265color
          GOOGLE_PROJECT_ID: bench-projects
          STAGING_GOOGLE_COMPUTE_ZONE: us-central1-a
          PRODUCTION_GOOGLE_COMPUTE_ZONE: europe-west1-b
    working_directory: ~/a_socials
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run application tests


