defaults: &defaults
  docker:
    - image: circleci/python:3.6.1
      environment:
        TERM: xterm-256color
  working_directory: ~/andela-socials-backend


version: 2
jobs:
  test:
      <<: *defaults
      - image: circleci/postgres:9.4
        environment:
          - TERM: xterm-256color
          - POSTGRES_USER: circleci
          - POSTGRES_DB: circlecidb
          - POSTGRES_PASSWORD: $DB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r server/requirements.txt
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            export DJANGO_SETTINGS_MODULE=a_socials.settings.dev
            python server/manage.py test --snapshot-update server/api/tests/ server/graphql_schemas/tests/

      - store_artifacts:
          path: test-reports
          destination: test-reports

  deploy:
    <<: *defaults
    working_directory: ~/repo
    steps:
    - checkout
    - setup_remote_docker
    - run


workflows:
    version: 2
    test_and_deploy:
        jobs:
            - test
            - deploy:
                requires:
                    - test
                filters:
                    branches:
                        only:
                            - master
                            - /release\/v[0-9].[0-9].[0-9]/
