version: '3'

volumes:
    postgres_data: {}
    postgres_backup: {}
    static_dir: {}

services:
  application:
    container_name: prod_andela_socials
    build:
      context: ../../
      dockerfile: docker/prod/Dockerfile
    env_file:
      - ../../.env
    ports:
      - "8000:8000"
    depends_on:
      - database
    volumes:
      - static_dir:/andela_social/staticfiles

  database:
    container_name: prod_andela_socials_db
    build:
      context: ../../docker/database
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ../../.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    ports:
      - "8093:5432"
  
  nginx:
    container_name: nginx_server
    build: ../nginx
    depends_on:
      - application
    ports:
      - "0.0.0.0:80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - static_dir:/andela_social/staticfiles
      