version: '3'

volumes:
    postgres_data: {}
    postgres_backup: {}
    static_dir: {}

services:
  application:
    container_name: prod_andela_socials
    build:
      context: ../../
      dockerfile: docker/prod/Dockerfile
    links:
     - database
    env_file:
      - ../../.env
    environment:
      - VIRTUAL_HOST=localhost
    # ports:
    #   - "8000:8000"
    expose:
      - "80"
    depends_on:
      - database
    volumes:
      - static_dir:/andela_social/staticfiles

  database:
    container_name: prod_andela_socials_db
    build:
      context: ../../docker/database
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ../../.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    expose:
      - "5432"
  
  nginx:
    container_name: nginx_server
    build: ../../docker/nginx
    depends_on:
      - application
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - static_dir:/andela_social/staticfiles
