version: "3"

services:
  server:
    build:
      context: ../../
      dockerfile: docker/release/server/Dockerfile
    depends_on:
        - database
    env_file:
        - ./prod.env
    environment:
      - DJANGO_SETTINGS_MODULE=a_socials.settings.prod
    command: gunicorn --bind 0.0.0.0:8000 a_socials.wsgi:application
    ports:
        - 8000:8000

  database:
    image: postgres
    restart: always
    expose:
        - "5432"
    environment:
        - POSTGRES_USER=a_social
        - POSTGRES_PASSWORD=a_social
        - POSTGRES_DB=a_social
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 5s
        timeout: 10s
        retries: 5
