FROM node:8 as builder

WORKDIR /app/


# Requirements have to be pulled and installed here, otherwise caching won't work
COPY package.json /app/

RUN npm install --save

# Load project files to new work directory
COPY . /app

RUN npm run start

FROM nginx:1.13.8
RUN rm /etc/nginx/conf.d/default.conf
COPY --from=builder /app/nginx.conf /etc/nginx/conf.d
COPY --from=builder /app/client/dist/ /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
